var _ = {};
_.editor = {};
_.editor.setTheme;
_.editor.setSession;
_.editor.getSession = {};
_.editor.getSession.setMode;
_.editor.getSession.setTabSize;
_.editor.getSession.setUseWrapMode;
_.editor.setOptions;
_.editor.session = {};
_.editor.session.setValue;
_.editor.session.getValue;
_.editor.getValue;
_.editor.gotoLine;
_.editor.focus;
_.editor.selection = {};
_.editor.selection.getCursor;
_.editor.selection.moveCursorToPosition;
var Ractive = {};
Ractive.DEBUG;
_.jsBody = {};
_.jsBody.resetTemplate;
_.jsBody.set;
_.jsBody.once;
var bootstrapToggle;
var SocialShareKit = {};
SocialShareKit.init;
var el;
var data;
var template;
var status;
var counterLines;
var counterLabels;
var addColor;
var recapLines;
recapLines.countered;
var recapLabels;
var connectWith;
var revert;
var receive;
var opacity;
var cursor;
var revert;
var revertDuration;
var accept;
var tolerance;
var greedy;
var helper;
var drop;
var over;
var out;
var click_startEditor;
_.myVarRecap;
_.recap_array = {};
_.doneEditingFunction;
-//_.onselectChangedTheme;
-//_.onselectChangedFontSize;
-//_.onclickRECAPULATR;
-//_.onclickAE;
-//_.onclickVIEWER;
-//_.onclickABOUT;
-//_.onclickCONTACT;
-//_.exampleRecap;
-//_.exampleRecapEnd;
-//_.submitRecap;
-//_.redrawRecap;
-//_.recap_array.ae;
